---
- name: "Installing homebrew taps"
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ taps }}"

- name: "Updating homebrew"
  homebrew:
    update_homebrew: yes
  changed_when: no

- name: "Installing homebrew packages"
  homebrew:
    name: "{{ brews }}"
    state: present

- name: "Installing homebrew casks"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ casks }}"
  register: result
  failed_when:
    - result.failed
    - not(result.msg is search("It seems there is already an App at"))
...
