---
- name: "Installing java"
  homebrew_cask:
    name: java
    state: present

- name: "Installing homebrew taps"
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ taps }}"

- name: "Updating homebrew"
  homebrew:
    update_homebrew: yes

- name: "Installing homebrew packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ brews }}"

- name: "Installing homebrew casks"
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ casks }}"
...
