---
- name: Ensure .ssh folder exists
  ansible.builtin.shell:
    cmd: mkdir ~/.ssh || true
- name: Generating ssh keys
  openssh_keypair:
    path: ~/.ssh/id_rsa
    force: no
    type: rsa
    size: 2048
